// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNNDVOSCqnI3xbb6rt2gJxkDeZQSSgALk',
    appId: '1:38171146362:web:00fd2a895ad8b56bdea3c3',
    messagingSenderId: '38171146362',
    projectId: 'watercan-delivery-app',
    authDomain: 'watercan-delivery-app.firebaseapp.com',
    storageBucket: 'watercan-delivery-app.firebasestorage.app',
    measurementId: 'G-B9SDKB0TXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPFQppJZO5ODZh-3rYOBuz34BlnNHphXA',
    appId: '1:38171146362:android:72535ba3ddcbfa68dea3c3',
    messagingSenderId: '38171146362',
    projectId: 'watercan-delivery-app',
    storageBucket: 'watercan-delivery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUR4jOcHHRC-HODn9NJXVGv2DYRxACDP8',
    appId: '1:38171146362:ios:8c74e3a9bce2d32bdea3c3',
    messagingSenderId: '38171146362',
    projectId: 'watercan-delivery-app',
    storageBucket: 'watercan-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.waterCanDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUR4jOcHHRC-HODn9NJXVGv2DYRxACDP8',
    appId: '1:38171146362:ios:8c74e3a9bce2d32bdea3c3',
    messagingSenderId: '38171146362',
    projectId: 'watercan-delivery-app',
    storageBucket: 'watercan-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.waterCanDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNNDVOSCqnI3xbb6rt2gJxkDeZQSSgALk',
    appId: '1:38171146362:web:1677989befe554ebdea3c3',
    messagingSenderId: '38171146362',
    projectId: 'watercan-delivery-app',
    authDomain: 'watercan-delivery-app.firebaseapp.com',
    storageBucket: 'watercan-delivery-app.firebasestorage.app',
    measurementId: 'G-YD5PPNRT4G',
  );
}
