/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class", 
  theme: { 
    extend: { 
      colors: { 
        "surface-container-highest": "#e0e3e5", 
        "surface-bright": "#f7f9fb", 
        "secondary-fixed": "#6ffbbe", 
        "primary-fixed": "#cce5ff", 
        "surface-container": "#eceef0", 
        "tertiary": "#545c72", 
        "surface-container-high": "#e6e8ea", 
        "surface": "#f7f9fb", 
        "on-primary": "#ffffff", 
        "on-surface-variant": "#3f4850", 
        "inverse-on-surface": "#eff1f3", 
        "on-secondary": "#ffffff", 
        "tertiary-container": "#6c748b", 
        "on-primary-fixed-variant": "#004b73", 
        "primary-fixed-dim": "#93ccff", 
        "on-error": "#ffffff", 
        "on-primary-fixed": "#001d31", 
        "on-surface": "#191c1e", 
        "surface-variant": "#e0e3e5", 
        "on-tertiary-fixed": "#131b2e", 
        "error-container": "#ffdad6", 
        "on-tertiary-container": "#fefcff", 
        "outline-variant": "#bfc7d2", 
        "secondary-fixed-dim": "#4edea3", 
        "background": "#f7f9fb", 
        "tertiary-fixed": "#dae2fd", 
        "on-tertiary": "#ffffff", 
        "surface-container-low": "#f2f4f6", 
        "on-tertiary-fixed-variant": "#3f465c", 
        "secondary": "#006c49", 
        "outline": "#707881", 
        "surface-tint": "#006398", 
        "primary": "#006194", 
        "primary-container": "#007bb9", 
        "surface-container-lowest": "#ffffff", 
        "on-secondary-container": "#00714d", 
        "secondary-container": "#6cf8bb", 
        "inverse-surface": "#2d3133", 
        "error": "#ba1a1a", 
        "inverse-primary": "#93ccff", 
        "on-error-container": "#93000a", 
        "tertiary-fixed-dim": "#bec6e0", 
        "surface-dim": "#d8dadc", 
        "on-secondary-fixed": "#002113", 
        "on-background": "#191c1e", 
        "on-secondary-fixed-variant": "#005236", 
        "on-primary-container": "#fdfcff" 
      }, 
      borderRadius: { 
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem" 
      }, 
      spacing: { 
        "gutter-sm": "1rem", 
        "space-xl": "2rem", 
        "margin": "2rem", 
        "space-md": "1rem", 
        "space-lg": "1.5rem", 
        "margin-sm": "1rem", 
        "space-sm": "0.5rem", 
        "gutter": "1.5rem", 
        "space-xs": "0.25rem" 
      }, 
      fontFamily: { 
        "display-lg": ["Inter", "sans-serif"], 
        "body-md": ["Inter", "sans-serif"], 
        "body-lg": ["Inter", "sans-serif"], 
        "caption": ["Inter", "sans-serif"], 
        "headline-md": ["Inter", "sans-serif"], 
        "headline-lg": ["Inter", "sans-serif"], 
        "label-sm": ["Inter", "sans-serif"], 
        "headline-sm": ["Inter", "sans-serif"], 
        "label-md": ["Inter", "sans-serif"] 
      }, 
      fontSize: { 
        "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }], 
        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }], 
        "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }], 
        "caption": ["12px", { "lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "400" }], 
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }], 
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "700" }], 
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.025em", "fontWeight": "600" }], 
        "headline-sm": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.005em", "fontWeight": "600" }], 
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.005em", "fontWeight": "500" }] 
      } 
    } 
  },
  plugins: [],
}
